//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.OrderPro = new HashSet<OrderPro>();
        }

        public int ID { get; set; }

        [Display(Name = "Tên đăng nhập")]
        [Required(ErrorMessage = "Không được để trống")]
        public string TaiKhoan { get; set; }


        [Display(Name = "Họ Tên")]
        [Required(ErrorMessage = "Không được để trống")]
        public string HoTen { get; set; }

        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Không được để trống")]
        public string DiaChi { get; set; }

        [Display(Name = "Mail")]
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Độ dài {0} phải từ {2} đến {1} kí tự")]
        public string Mail { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Không được để trống")]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "Độ dài {0} phải từ {2} đến {1} kí tự")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }

        [NotMapped]
        [Compare("MatKhau")]
        [DataType(DataType.Password)]
        [DisplayName("Nhập lại mật khẩu: ")]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "Độ dài {0} phải từ {2} đến {1} kí tự")]
        public string NhaplaiMatKhau { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderPro { get; set; }
    }
}
