//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Infrastructure;


namespace DoAnPC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
   

    
    public partial class User
    {
       
        public int ID { get; set; }

        [Required(ErrorMessage ="Không được bỏ trống")]
        [StringLength(30)]
        [Display(Name = "Tài Khoản")]
        public string TaiKhoan  { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [StringLength(20)]
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [StringLength(50)]
        public string Mail { get; set; }

        [Required(ErrorMessage = "Không được bỏ trống")]
        [Display(Name = "Mật Khẩu")]
        [StringLength(30,MinimumLength =6, ErrorMessage ="Mật khẩu phải có độ dài từ {2} đến {1} kí tự")]
        public string MatKhau { get; set; }
    }
}


//namespace DoAnPC.Models
//{
//    using System;
//    using System.Collections.Generic;
//    using System.ComponentModel.DataAnnotations;
//    using System.ComponentModel.DataAnnotations.Schema;
//    using System.Data.Entity.Spatial;

//    [Table("User")]
//    public partial class User
//    {
//        [DatabaseGenerated(DatabaseGeneratedOption.None)]
//        public int ID { get; set; }

//        [Required]
//        [StringLength(30)]
//        //[Display(Name = "Tài Khoản")]
//        public string TaiKhoan { get; set; }

//        [Required]
//        [StringLength(50)]
//        //[Display(Name = "Họ Tên")]
//        public string HoTen { get; set; }

//        [Required]
//        [StringLength(50)]
//        public string Mail { get; set; }

//        [Required]
//        [StringLength(30)]
//        public string MatKhau { get; set; }
//    }
//}

